# Generated by Django 5.1.5 on 2025-01-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0003_card_login_pin_securenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cvv_nonce',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='card',
            name='cvv_tag',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='card',
            name='number_nonce',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='card',
            name='number_tag',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='login',
            name='password_nonce',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='login',
            name='password_tag',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='pin',
            name='code_cvv',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='pin',
            name='code_nonce',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='securenote',
            name='notes_nonce',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='securenote',
            name='notes_tag',
            field=models.CharField(default='', max_length=24),
        ),
    ]
