# Generated by Django 5.1.5 on 2025-01-29 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0004_card_cvv_nonce_card_cvv_tag_card_number_nonce_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='code_cvv',
            new_name='code_tag',
        ),
    ]
