# Generated by Django 5.1.5 on 2025-02-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0006_alter_card_id_alter_login_id_alter_pin_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
